### ISSUE TITLE
Broken links in malware recording pages

### ISSUE THREAD

**Issue by platonK** [moyix/panda-malrec#2]
I am not sure if this the appropriate place to report it, but there are some broken links in giantpanda.gtisc.gatech.edu/malrec and panda.gtisc.gatech.edu/malrec.

You can find in the ZIP attached a list of 15,163 broken VT links and 14,897 broken PCAP links.
[broken.zip](https://github.com/moyix/panda-malrec/files/1145975/broken.zip)

**Comment by moyix** [comment]
Thanks for the report. Some of the VT and PCAP files were lost when migrating things from panda to giantpanda – luckily they can be regenerated by re-querying VirusTotal (for VT links) and extracting the network data from the rr log (for PCAPS). I will try to do this soon.
