### ISSUE TITLE
Question about the argument: “-record-from bootsys:/home/brendan/malrec/logs/rr/${run_id}”

### ISSUE THREAD

**Issue by Reguix** [moyix/panda-malrec#3]
In the runmal.py:
panda_args = [panda_exe,
              '-m', conf.get('VM', 'mem'),
              '-monitor', 'telnet:localhost:{0},server,nowait'.format(monitor_port),
              '-drive', 'file={0},cache=unsafe'.format(new_qcow),
              '-record-from', 'bootsys:{0}'.format(rr_logname),
              '-net', 'nic,model=e1000',
              '-net', 'dump,file={0}'.format(pcap_name),
              '-net', 'user',
              '-vnc', '127.0.0.1:{0}'.format(instance),
              ]
I don't understand the argument "-record-from bootsys:/home/brendan/malrec/logs/rr/${run_id}" in the command /home/brendan/git/panda/qemu/x86_64-softmmu/qemu-system-x86_64 and I get the error in d766b5e0-fc7d-4e75-9048-dc76d26729a3.stdout like this:
loading snapshot:	bootsys
Error loading snapshot! Failed to begin recording. Code: `-2`

Then I remove this argument and add these code in runmal.py: 
logging.info('Begin` record.')
mon_cmd('begin_record {0}\n'.format(rr_logname), `mon)

Also in the VM of win7.base.qcow2, I set the cmd.exe automaticly executes with system starting up. 

Then I have another question: before the VM of win7.base.qcow2 starts up completely and cmd.exe executes, these commands such as  "change ide1-cd0 {0}", "ipconfig /renew", "copy D:\{0} C:\Users\qemu\Desktop" are invalid. I am confused about this. Should I add code like time.sleep() to wait the system starts up completely? Hope for your help!

**Comment by moyix** [comment]
The `-record-from` argument loads a snapshot (in this case, `bootsys`) and immediately begins a recording. The error you're getting indicates that your QCOW doesn't have a snapshot named `bootsys`. In my setup, `bootsys` is a snapshot that already has the `cmd.exe` window open with Administrator privileges.

**Comment by Reguix** [comment]
I get it! Thank you very much !
